### PR TITLE
Allow for Project name containing whitespaces.

### PR DESCRIPTION
**Pull request by Joaqim**
I just simply made sure that "$project" will always be used as a string.

### CODE REVIEW

**Comment by Joaqim** [comment]
Just noticed there is a bug when building, will try to sort that out.

**Comment by nonunknown** [comment]
you cant use whitspaces on your project name, since its used to generate the library name in the code, need to check that! you have tested and worked fine inside godot?

**Comment by Joaqim** [comment]
One potential fix would be to just replace any whitespace with '_':
```
# Project name in lower- and uppercase
projectLower="${project,,}"
projectUpper="${project^^}"

# Replace any whitespace with _
projectLower="${projectLower// /_}"
projectUpper="${projectUpper// /_}"
```

The reason I went opened this fork is that when I created my project, let's call it 'My Project', the script created two separate folders - 'My' & 'Project' - that's an easy bug fix.

But then I would also expect my Project folder to stay exactly as I typed, so I would expect the result to be:
My Project/build.sh 
My Project/...

And the Library to be called either: MyLibrary.gdextension or my_library.gdextension
As I'm new to Godot, I leave those specifications up to you.

**Comment by nonunknown** [comment]
ok, I'll test today later on, and merge if everything is fine

**Comment by nonunknown** [comment]
Just approved! awesome work, thanks for your contribution!!!!

**Pull request merged**
